Module Excercise6
    'Brooks Keller
    'Excercise 6
    '9/15/2023
    Sub main()
        Console.WriteLine("Brooks Keller" & vbNewLine)
        Console.WriteLine("1. Knock, Knock")
        Console.ReadLine()
        Console.WriteLine("Who's there?")
        Console.ReadLine()
        Console.WriteLine("Olive")
        Console.ReadLine()
        Console.WriteLine("Olive who?")
        Console.ReadLine()
        Console.WriteLine("Olive you and miss you!")
        Console.ReadLine()
        Console.WriteLine("2. Knock, Knock")
        Console.ReadLine()
        Console.WriteLine("Who's there?")
        Console.ReadLine()
        Console.WriteLine("Lettuce")
        Console.ReadLine()
        Console.WriteLine("Lettuce who?")
        Console.ReadLine()
        Console.WriteLine("Lettuce in, it's cold out here!")
        Console.ReadLine()
        Console.WriteLine("3. Knock, Knock")
        Console.ReadLine()
        Console.WriteLine("Who's there?")
        Console.ReadLine()
        Console.WriteLine("Honeydew")
        Console.ReadLine()
        Console.WriteLine("Honeydew who?")
        Console.ReadLine()
        Console.WriteLine("Honeydew you want to hear another joke?")
        Console.ReadLine()
        Console.WriteLine("4. Knock, Knock")
        Console.ReadLine()
        Console.WriteLine("Who's there?")
        Console.ReadLine()
        Console.WriteLine("Boo")
        Console.ReadLine()
        Console.WriteLine("Boo who?")
        Console.ReadLine()
        Console.WriteLine("Don't cry its just a joke!!")
        Console.ReadLine()
        Console.WriteLine("5. Knock, Knock")
        Console.ReadLine()
        Console.WriteLine("Who's there?")
        Console.ReadLine()
        Console.WriteLine("Atch")
        Console.ReadLine()
        Console.WriteLine("Atch who?")
        Console.ReadLine()
        Console.WriteLine("Bless you!")
    End Sub
End Module
